#include "structures/glitched/Cleanup.h"

#include "Config.h"
#include "Random.h"
#include "World.h"
#include "ids/Paint.h"
#include "structures/StructureUtil.h"
#include "vendor/frozen/set.h"

constexpr inline auto glitchedSprites = frozen::make_set<int>({
    TileID::alchemyTable,
    TileID::altar,
    TileID::bastStatue,
    TileID::bathtub,
    TileID::bed,
    TileID::bench,
    TileID::bewitchingTable,
    TileID::boneWelder,
    TileID::bookcase,
    TileID::boulder,
    TileID::bouncyBoulder,
    TileID::candelabra,
    TileID::catacomb,
    TileID::chair,
    TileID::chandelier,
    TileID::chest,
    TileID::chestGroup2,
    TileID::clock,
    TileID::detonator,
    TileID::door,
    TileID::dresser,
    TileID::explosives,
    TileID::friendlyBoulder,
    TileID::ghoulder,
    TileID::hellforge,
    TileID::hugeDragonEgg,
    TileID::lamp,
    TileID::lantern,
    TileID::largePile,
    TileID::largePileGroup2,
    TileID::larva,
    TileID::lavaBoulder,
    TileID::lifeCrystal,
    TileID::lifeCrystalBoulder,
    TileID::lihzahrdAltar,
    TileID::livingLoom,
    TileID::loom,
    TileID::manaCrystal,
    TileID::minecartTrack,
    TileID::orbHeart,
    TileID::painting2x3,
    TileID::painting3x2,
    TileID::painting3x3,
    TileID::painting6x4,
    TileID::piano,
    TileID::pot,
    TileID::pressurePlate,
    TileID::rainbowBoulder,
    TileID::sharpeningStation,
    TileID::sink,
    TileID::skyMill,
    TileID::sleepingDigtoise,
    TileID::spiderBoulder,
    TileID::statue,
    TileID::table,
    TileID::tableGroup2,
    TileID::TNTBarrel,
    TileID::toilet,
    TileID::workBench,
});

constexpr inline std::array glitchedTiles{
    TileID::adamantiteOre,
    TileID::aetherium,
    TileID::amberGemspark,
    TileID::amethystGemspark,
    TileID::amethystStone,
    TileID::argonMossBrick,
    TileID::argonMossStone,
    TileID::ash,
    TileID::ashGrass,
    TileID::ashWood,
    TileID::asphalt,
    TileID::blueBrick,
    TileID::blueDynastyShingles,
    TileID::blueMossStone,
    TileID::borealWood,
    TileID::brownMossStone,
    TileID::candyCane,
    TileID::chlorophyteOre,
    TileID::clay,
    TileID::cloud,
    TileID::cobaltOre,
    TileID::cobweb,
    TileID::copperOre,
    TileID::coralstone,
    TileID::corruptGrass,
    TileID::corruptIce,
    TileID::crackedBlueBrick,
    TileID::crackedGreenBrick,
    TileID::crackedPinkBrick,
    TileID::crimsand,
    TileID::crimsandstone,
    TileID::crimsonGrass,
    TileID::crimsonIce,
    TileID::crimstone,
    TileID::crimstoneBrick,
    TileID::crimtane,
    TileID::crispyHoney,
    TileID::crystalBlock,
    TileID::decorativeCobweb,
    TileID::demonite,
    TileID::desertFossil,
    TileID::diamondGemspark,
    TileID::diamondStone,
    TileID::dirt,
    TileID::dirtiestBlock,
    TileID::dynastyWood,
    TileID::ebonsand,
    TileID::ebonsandstone,
    TileID::ebonstone,
    TileID::ebonstoneBrick,
    TileID::emeraldGemspark,
    TileID::emeraldStone,
    TileID::flesh,
    TileID::glowingMushroom,
    TileID::goldOre,
    TileID::goldStarry,
    TileID::granite,
    TileID::grass,
    TileID::grate,
    TileID::grayBrick,
    TileID::grayStucco,
    TileID::greenBrick,
    TileID::greenCandyCane,
    TileID::greenMossStone,
    TileID::hallowedGrass,
    TileID::hallowedIce,
    TileID::hardenedCrimsand,
    TileID::hardenedEbonsand,
    TileID::hardenedPearlsand,
    TileID::hardenedSand,
    TileID::heliumMossStone,
    TileID::hellstone,
    TileID::hellstoneBrick,
    TileID::hive,
    TileID::honey,
    TileID::ice,
    TileID::iceBrick,
    TileID::iridescentBrick,
    TileID::ironBrick,
    TileID::ironOre,
    TileID::jungleGrass,
    TileID::kryptonMossBrick,
    TileID::kryptonMossStone,
    TileID::lavaMossStone,
    TileID::leadOre,
    TileID::leaf,
    TileID::lesion,
    TileID::lihzahrdBrick,
    TileID::livingMahogany,
    TileID::livingWood,
    TileID::mahoganyLeaf,
    TileID::marble,
    TileID::martianConduitPlating,
    TileID::meteorite,
    TileID::mud,
    TileID::mudstoneBrick,
    TileID::mushroomGrass,
    TileID::mythrilOre,
    TileID::neonMossBrick,
    TileID::neonMossStone,
    TileID::obsidian,
    TileID::obsidianBrick,
    TileID::offlineAmethystGemspark,
    TileID::offlineRubyGemspark,
    TileID::offlineSapphireGemspark,
    TileID::orichalcumOre,
    TileID::palladiumOre,
    TileID::palmWood,
    TileID::pearlsand,
    TileID::pearlsandstone,
    TileID::pearlstone,
    TileID::pearlstoneBrick,
    TileID::pineTree,
    TileID::pineWood,
    TileID::pinkBrick,
    TileID::pinkSlime,
    TileID::platinumOre,
    TileID::purpleMossStone,
    TileID::rainCloud,
    TileID::rainbowBrick,
    TileID::redBrick,
    TileID::redDynastyShingles,
    TileID::redMossStone,
    TileID::redStucco,
    TileID::richMahogany,
    TileID::rubyGemspark,
    TileID::rubyStone,
    TileID::sand,
    TileID::sandstone,
    TileID::sandstoneBrick,
    TileID::sandstoneSlab,
    TileID::sapphireGemspark,
    TileID::sapphireStone,
    TileID::shellPile,
    TileID::sillyGreenBalloon,
    TileID::sillyPinkBalloon,
    TileID::sillyPurpleBalloon,
    TileID::silt,
    TileID::silverOre,
    TileID::slime,
    TileID::slush,
    TileID::smoothGranite,
    TileID::smoothMarble,
    TileID::snow,
    TileID::snowBrick,
    TileID::snowCloud,
    TileID::spiderNest,
    TileID::spike,
    TileID::stone,
    TileID::stoneSlab,
    TileID::sunplate,
    TileID::thinIce,
    TileID::tinBrick,
    TileID::tinOre,
    TileID::titaniumOre,
    TileID::titanstone,
    TileID::topazGemspark,
    TileID::topazStone,
    TileID::tungstenOre,
    TileID::waterfall,
    TileID::wood,
    TileID::woodenSpike,
    TileID::xenonMossStone,
};

constexpr inline std::array glitchedPaints{
    Paint::black,
    Paint::blue,
    Paint::brown,
    Paint::cyan,
    Paint::gray,
    Paint::green,
    Paint::lime,
    Paint::negative,
    Paint::orange,
    Paint::pink,
    Paint::purple,
    Paint::red,
    Paint::skyBlue,
    Paint::teal,
    Paint::violet,
    Paint::white,
    Paint::yellow,
};

void applyGlitchedFinalize(int x, int y, Random &rnd, World &world)
{
    if (!world.conf.glitched) {
        return;
    }
    Tile &tile = world.getTile(x, y);
    if ((tile.liquid == Liquid::honey || tile.liquid == Liquid::shimmer) &&
        !world.conf.celebration && !world.conf.hiveQueen) {
        tile.liquid =
            tile.liquid == Liquid::honey ? Liquid::shimmer : Liquid::honey;
    }

    int randInt = 99999 * (2 + rnd.getFineNoise(x, y));
    if (glitchedSprites.contains(tile.blockID) && randInt % 13 == 0) {
        tile.echoCoatBlock = true;
    }
    if (isSolidBlock(tile.blockID)) {
        if (!world.getFramedTiles()[tile.blockID] && randInt % 5659 < 10) {
            tile.blockID = glitchedTiles[randInt % glitchedTiles.size()];
        }
        if (tile.blockPaint == Paint::none && randInt % 1327 == 0) {
            tile.blockPaint = glitchedPaints[randInt % glitchedPaints.size()];
        }
    }
}
