#include "structures/glitched/LootRules.h"

#include "Config.h"
#include "Random.h"
#include "World.h"
#include "ids/ItemID.h"
#include "ids/Prefix.h"
#include "vendor/frozen/set.h"
#include <iostream>

Item getAltPrimaryLoot(Random &rnd)
{
    return rnd.select<Item>({
        {ItemID::bloodyMachete, rnd.select(PrefixSet::universal), 1},
        {ItemID::chainKnife, rnd.select(PrefixSet::universal), 1},
        {ItemID::code1, rnd.select(PrefixSet::universal), 1},
        {ItemID::combatWrench, rnd.select(PrefixSet::universal), 1},
        {ItemID::grayZapinator, rnd.select(PrefixSet::magic), 1},
        {ItemID::paintballGun, rnd.select(PrefixSet::ranged), 1},
        {ItemID::slimeStaff, rnd.select(PrefixSet::summon), 1},
        {ItemID::stylishScissors, rnd.select(PrefixSet::melee), 1},
        {ItemID::terragrim, rnd.select(PrefixSet::common), 1},
        {ItemID::vampireFrogStaff, rnd.select(PrefixSet::summon), 1},
        {ItemID::antiGravityHook, Prefix::none, 1},
        {ItemID::hookOfDissonance, Prefix::none, 1},
        {ItemID::staticHook, Prefix::none, 1},
        {ItemID::reaverShark, rnd.select(PrefixSet::melee), 1},
        {ItemID::sawtoothShark, rnd.select(PrefixSet::common), 1},
        {ItemID::gravediggersShovel, rnd.select(PrefixSet::melee), 1},
        {ItemID::fartInABalloon, rnd.select(PrefixSet::accessory), 1},
        {ItemID::jetpack, rnd.select(PrefixSet::accessory), 1},
        {ItemID::magicQuiver, rnd.select(PrefixSet::accessory), 1},
        {ItemID::moonCharm, rnd.select(PrefixSet::accessory), 1},
        {ItemID::yoyoGlove, rnd.select(PrefixSet::accessory), 1},
        {ItemID::lawnFlamingo, Prefix::none, 1},
        {ItemID::strangePlantPurple, Prefix::none, 1},
        {ItemID::strangePlantOrange, Prefix::none, 1},
        {ItemID::strangePlantGreen, Prefix::none, 1},
        {ItemID::strangePlantRed, Prefix::none, 1},
        {ItemID::universalPylon, Prefix::none, 1},
        {ItemID::kwadRacerDrone, Prefix::none, 1},
        {ItemID::magicHat, Prefix::none, 1},
        {ItemID::ultrabrightHelmet, Prefix::none, 1},
        {ItemID::wizardHat, Prefix::none, 1},
        {ItemID::magicLantern, Prefix::none, 1},
    });
}

int getAltSecondaryLoot(int stack, Random &rnd)
{
    if (stack > 55) {
        return rnd.select({
            ItemID::antiPortalBlock,   ItemID::ashWood,
            ItemID::astraBrick,        ItemID::bamboo,
            ItemID::borealWood,        ItemID::cactus,
            ItemID::chlorophyteBrick,  ItemID::cobaltBrick,
            ItemID::cosmicEmberBrick,  ItemID::crackedBlueBrick,
            ItemID::crackedGreenBrick, ItemID::crackedPinkBrick,
            ItemID::cryocoreBrick,     ItemID::darkCelestialBrick,
            ItemID::dynastyWood,       ItemID::ebonwood,
            ItemID::echoBlock,         ItemID::explosives,
            ItemID::feywood,           ItemID::glowingMushroom,
            ItemID::gothicBrick,       ItemID::grate,
            ItemID::hallowedBrick,     ItemID::hay,
            ItemID::heavenforgeBrick,  ItemID::jellyfishBlock,
            ItemID::luminiteBrick,     ItemID::lunarRustBrick,
            ItemID::mercuryBrick,      ItemID::mythrilBrick,
            ItemID::nebulaBrick,       ItemID::palmWood,
            ItemID::pearlstoneBrick,   ItemID::pearlwood,
            ItemID::pineWood,          ItemID::pumpkin,
            ItemID::richMahogany,      ItemID::shadewood,
            ItemID::sharpSpikeBlock,   ItemID::siltBlock,
            ItemID::slushBlock,        ItemID::solarBrick,
            ItemID::spookyWood,        ItemID::starRoyaleBrick,
            ItemID::stardustBrick,     ItemID::toybreakerBrick,
            ItemID::vortexBrick,       ItemID::wood,
        });
    } else if (stack > 34) {
        return rnd.select({
            ItemID::blackPaint,
            ItemID::blueFlare,
            ItemID::bluePaint,
            ItemID::blueSolution,
            ItemID::brownPaint,
            ItemID::brownSolution,
            ItemID::cursedFlare,
            ItemID::cyanPaint,
            ItemID::darkBlueSolution,
            ItemID::deepBluePaint,
            ItemID::deepCyanPaint,
            ItemID::deepGreenPaint,
            ItemID::deepLimePaint,
            ItemID::deepOrangePaint,
            ItemID::deepPinkPaint,
            ItemID::deepPurplePaint,
            ItemID::deepRedPaint,
            ItemID::deepSkyBluePaint,
            ItemID::deepTealPaint,
            ItemID::deepVioletPaint,
            ItemID::deepYellowPaint,
            ItemID::echoCoating,
            ItemID::flare,
            ItemID::grayPaint,
            ItemID::greenPaint,
            ItemID::greenSolution,
            ItemID::illuminantCoating,
            ItemID::limePaint,
            ItemID::negativePaint,
            ItemID::orangePaint,
            ItemID::pinkPaint,
            ItemID::purplePaint,
            ItemID::purpleSolution,
            ItemID::rainbowFlare,
            ItemID::redPaint,
            ItemID::redSolution,
            ItemID::shadowPaint,
            ItemID::shimmerFlare,
            ItemID::skyBluePaint,
            ItemID::spelunkerFlare,
            ItemID::tealPaint,
            ItemID::violetPaint,
            ItemID::whitePaint,
            ItemID::whiteSolution,
            ItemID::yellowPaint,
            ItemID::yellowSolution,
        });
    } else if (stack > 21) {
        return rnd.select({
            ItemID::boneArrow,
            ItemID::chlorophyteArrow,
            ItemID::chlorophyteBullet,
            ItemID::crystalBullet,
            ItemID::crystalDart,
            ItemID::cursedArrow,
            ItemID::cursedBullet,
            ItemID::cursedDart,
            ItemID::explodingBullet,
            ItemID::flamingArrow,
            ItemID::frostburnArrow,
            ItemID::goldenBullet,
            ItemID::hellfireArrow,
            ItemID::highVelocityBullet,
            ItemID::holyArrow,
            ItemID::ichorArrow,
            ItemID::ichorBullet,
            ItemID::ichorDart,
            ItemID::jestersArrow,
            ItemID::luminiteArrow,
            ItemID::luminiteBullet,
            ItemID::meteorShot,
            ItemID::musketBall,
            ItemID::nanoBullet,
            ItemID::partyBullet,
            ItemID::poisonDart,
            ItemID::seed,
            ItemID::shimmerArrow,
            ItemID::silverBullet,
            ItemID::tungstenBullet,
            ItemID::unholyArrow,
            ItemID::venomArrow,
            ItemID::venomBullet,
            ItemID::woodenArrow,
        });
    } else if (stack > 13) {
        return rnd.select({
            ItemID::adamantiteOre,
            ItemID::bloodWater,
            ItemID::buggy,
            ItemID::chlorophyteOre,
            ItemID::cobaltOre,
            ItemID::copperOre,
            ItemID::crimtaneOre,
            ItemID::demoniteOre,
            ItemID::enchantedNightcrawler,
            ItemID::goldOre,
            ItemID::hellstone,
            ItemID::holyWater,
            ItemID::ironOre,
            ItemID::journeymanBait,
            ItemID::juliaButterfly,
            ItemID::lavafly,
            ItemID::leadOre,
            ItemID::lightningBug,
            ItemID::luminite,
            ItemID::magmaSnail,
            ItemID::meteorite,
            ItemID::mythrilOre,
            ItemID::obsidian,
            ItemID::orichalcumOre,
            ItemID::palladiumOre,
            ItemID::platinumOre,
            ItemID::purificationPowder,
            ItemID::purpleEmperorButterfly,
            ItemID::redAdmiralButterfly,
            ItemID::silverOre,
            ItemID::sluggy,
            ItemID::tinOre,
            ItemID::titaniumOre,
            ItemID::tungstenOre,
            ItemID::unholyWater,
            ItemID::viciousPowder,
            ItemID::vilePowder,
            ItemID::worm,
        });
    } else if (stack > 8) {
        return rnd.select({
            ItemID::adamantiteBar,
            ItemID::argonMoss,
            ItemID::ashGrassSeeds,
            ItemID::blueFlowerSeeds,
            ItemID::blueMoss,
            ItemID::brownMoss,
            ItemID::chlorophyteBar,
            ItemID::cobaltBar,
            ItemID::copperBar,
            ItemID::corruptSeeds,
            ItemID::crimsonSeeds,
            ItemID::crimtaneBar,
            ItemID::demoniteBar,
            ItemID::goldBar,
            ItemID::grassSeeds,
            ItemID::greenMoss,
            ItemID::hallowedBar,
            ItemID::hallowedSeeds,
            ItemID::heliumMoss,
            ItemID::hellstoneBar,
            ItemID::ironBar,
            ItemID::jungleGrassSeeds,
            ItemID::kryptonMoss,
            ItemID::lavaMoss,
            ItemID::leadBar,
            ItemID::luminiteBar,
            ItemID::magentaFlowerSeeds,
            ItemID::meteoriteBar,
            ItemID::mushroomGrassSeeds,
            ItemID::mythrilBar,
            ItemID::neonMoss,
            ItemID::orichalcumBar,
            ItemID::palladiumBar,
            ItemID::pinkFlowerSeeds,
            ItemID::platinumBar,
            ItemID::purpleMoss,
            ItemID::redFlowerSeeds,
            ItemID::redMoss,
            ItemID::shroomiteBar,
            ItemID::silverBar,
            ItemID::spectreBar,
            ItemID::tallGrassSeeds,
            ItemID::tinBar,
            ItemID::titaniumBar,
            ItemID::tungstenBar,
            ItemID::violetFlowerSeeds,
            ItemID::whiteFlowerSeeds,
            ItemID::wildFlowerSeeds,
            ItemID::xenonMoss,
            ItemID::yellowFlowerSeeds,
        });
    } else if (stack > 5) {
        return rnd.select({
            ItemID::amber,
            ItemID::amberGemcorn,
            ItemID::amethyst,
            ItemID::amethystGemcorn,
            ItemID::armoredCavefish,
            ItemID::blinkroot,
            ItemID::blinkrootSeeds,
            ItemID::crimsonTigerfish,
            ItemID::damselfish,
            ItemID::daybloom,
            ItemID::daybloomSeeds,
            ItemID::deathweed,
            ItemID::deathweedSeeds,
            ItemID::diamond,
            ItemID::diamondGemcorn,
            ItemID::doubleCod,
            ItemID::ebonkoi,
            ItemID::emerald,
            ItemID::emeraldGemcorn,
            ItemID::fertilizer,
            ItemID::fireblossom,
            ItemID::fireblossomSeeds,
            ItemID::flarefinKoi,
            ItemID::frostMinnow,
            ItemID::hemopiranha,
            ItemID::infusedFertilizer,
            ItemID::moonglow,
            ItemID::moonglowSeeds,
            ItemID::obsidifish,
            ItemID::princessFish,
            ItemID::prismite,
            ItemID::pumpkinSeed,
            ItemID::ruby,
            ItemID::rubyGemcorn,
            ItemID::sakuraSapling,
            ItemID::sapphire,
            ItemID::sapphireGemcorn,
            ItemID::shiverthorn,
            ItemID::shiverthornSeeds,
            ItemID::specularFish,
            ItemID::stinkfish,
            ItemID::topaz,
            ItemID::topazGemcorn,
            ItemID::variegatedLardfish,
            ItemID::waterleaf,
            ItemID::waterleafSeeds,
            ItemID::yellowWillowSapling,
        });
    } else if (stack > 3) {
        return rnd.select({
            ItemID::appleJuice,
            ItemID::archeryPotion,
            ItemID::battlePotion,
            ItemID::biomeSightPotion,
            ItemID::bloodyMoscato,
            ItemID::builderPotion,
            ItemID::cartonOfMilk,
            ItemID::clusterRocketI,
            ItemID::clusterRocketII,
            ItemID::cratePotion,
            ItemID::dryRocket,
            ItemID::eggnog,
            ItemID::flaskOfGold,
            ItemID::flaskOfParty,
            ItemID::frozenBananaDaiquiri,
            ItemID::genderChangePotion,
            ItemID::greaterHealingPotion,
            ItemID::greaterLuckPotion,
            ItemID::greaterManaPotion,
            ItemID::heartreachPotion,
            ItemID::honeyRocket,
            ItemID::invisibilityPotion,
            ItemID::lavaRocket,
            ItemID::lemonade,
            ItemID::lovePotion,
            ItemID::marshmallowOnAStick,
            ItemID::peachSangria,
            ItemID::pinaColada,
            ItemID::smoothieOfDarkness,
            ItemID::soulOfFlight,
            ItemID::soulOfFright,
            ItemID::soulOfLight,
            ItemID::soulOfMight,
            ItemID::soulOfNight,
            ItemID::soulOfSight,
            ItemID::stinkPotion,
            ItemID::strangeBrew,
            ItemID::superHealingPotion,
            ItemID::superManaPotion,
            ItemID::tropicalSmoothie,
            ItemID::wetRocket,
        });
    }
    return rnd.select({
        ItemID::aetherMonolith,
        ItemID::aleTosser,
        ItemID::argonMossFishingBobber,
        ItemID::arkhalis,
        ItemID::axearang,
        ItemID::beeCloak,
        ItemID::beetleMinecart,
        ItemID::binoculars,
        ItemID::bladedGlove,
        ItemID::bloodRainBow,
        ItemID::boneSword,
        ItemID::bookOfSkulls,
        ItemID::bundledPartyBalloons,
        ItemID::candyCaneSword,
        ItemID::candyCornRifle,
        ItemID::cauldron,
        ItemID::chlorophyteExtractinator,
        ItemID::classyCane,
        ItemID::coffinMinecart,
        ItemID::coinGun,
        ItemID::crtMonolith,
        ItemID::crystalBall,
        ItemID::divingGear,
        ItemID::dyeVat,
        ItemID::exoticScimitar,
        ItemID::filmProjector,
        ItemID::fishFinder,
        ItemID::friendlyRainbowBoulder,
        ItemID::furnace,
        ItemID::gladius,
        ItemID::goblinTech,
        ItemID::gps,
        ItemID::gummyWorm,
        ItemID::handWarmer,
        ItemID::heavyAssembler,
        ItemID::heliumMossFishingBobber,
        ItemID::hiTekSunglasses,
        ItemID::hoverboard,
        ItemID::ironAnvil,
        ItemID::killingDeck,
        ItemID::kryptonMossFishingBobber,
        ItemID::lavaMossFishingBobber,
        ItemID::lawnMower,
        ItemID::leadAnvil,
        ItemID::loom,
        ItemID::luckyCoin,
        ItemID::magicString,
        ItemID::manaFlower,
        ItemID::meatGrinder,
        ItemID::mechanicalRuler,
        ItemID::meowmereMinecart,
        ItemID::mushroomStaff,
        ItemID::musicBoxRainbowBoulder,
        ItemID::musicBoxSilence,
        ItemID::musicBoxTorchGod,
        ItemID::musicBoxWindyDay,
        ItemID::neonMossFishingBobber,
        ItemID::neptunesShell,
        ItemID::otherworldlyMusicBoxSpace,
        ItemID::otherworldlyMusicBoxTheTowers,
        ItemID::partyWagon,
        ItemID::pewMaticHorn,
        ItemID::philosophersStone,
        ItemID::pigronMinecart,
        ItemID::pirateHat,
        ItemID::presserator,
        ItemID::radioThing,
        ItemID::rainbowCursor,
        ItemID::redRyder,
        ItemID::rek3000,
        ItemID::replicaCrimsonAltar,
        ItemID::replicaDemonAltar,
        ItemID::resonanceScepter,
        ItemID::retroMonolith,
        ItemID::rifleScope,
        ItemID::rodOfDiscord,
        ItemID::ruler,
        ItemID::sandgun,
        ItemID::sawmill,
        ItemID::shimmerGun,
        ItemID::sillyTiedBundleOfBalloons,
        ItemID::silverWatch,
        ItemID::slapHand,
        ItemID::spectrePaintbrush,
        ItemID::spectrePaintRoller,
        ItemID::spectrePaintScraper,
        ItemID::steampunkMinecart,
        ItemID::teapot,
        ItemID::terraformer,
        ItemID::theDutchman,
        ItemID::toolbox,
        ItemID::trimarang,
        ItemID::tungstenWatch,
        ItemID::voidVault,
        ItemID::wafflesIron,
        ItemID::waterGun,
        ItemID::xenonMossFishingBobber,
    });
}

void randomizeLoot(Random &rnd, World &world)
{
    std::cout << "Scrambling loot\n";
    constexpr auto lockedItems = frozen::make_set<int>({
        ItemID::desertTigerStaff,
        ItemID::flyingCarpet,
        ItemID::piranhaGun,
        ItemID::rainbowGun,
        ItemID::sandstormInABottle,
        ItemID::scourgeOfTheCorruptor,
        ItemID::staffOfTheFrostHydra,
        ItemID::vampireKnives,
    });

    double primaryChance = std::min(0.3 * (world.conf.lootRandomizer - 1), 0.3);
    double secondaryChance =
        std::min(0.15 * (world.conf.lootRandomizer - 2), 0.3);
    std::vector<Chest> &chests = world.getChests();
    if (primaryChance > 0) {
        for (auto &chest : chests) {
            Item &primaryItem = chest.items.front();
            if (primaryItem.stack > 0 &&
                !lockedItems.contains(primaryItem.id) &&
                rnd.getDouble(0, 1) < primaryChance) {
                primaryItem = getAltPrimaryLoot(rnd);
            }
            if (secondaryChance > 0) {
                for (auto &item : chest.items) {
                    if (item.stack > 0 && !lockedItems.contains(item.id) &&
                        rnd.getDouble(0, 1) < secondaryChance) {
                        item.id = getAltSecondaryLoot(item.stack, rnd);
                        item.prefix = Prefix::none;
                    }
                }
            }
        }
    }

    double shuffleChance = std::min(0.3 * world.conf.lootRandomizer, 0.3);
    for (size_t idx = 0; idx + 1 < chests.size(); ++idx) {
        for (auto &item : chests[idx].items) {
            if (item.stack <= 0 || lockedItems.contains(item.id) ||
                rnd.getDouble(0, 1) > shuffleChance) {
                continue;
            }
            auto &destItems =
                chests[rnd.getInt(idx + 1, chests.size() - 1)].items;
            int lastFilledSlot = destItems.size() - 1;
            while (lastFilledSlot >= 0 &&
                   destItems[lastFilledSlot].stack <= 0) {
                --lastFilledSlot;
            }
            if (lastFilledSlot < 0) {
                continue;
            }
            auto &destItem = destItems[rnd.getInt(0, lastFilledSlot)];
            if (!lockedItems.contains(destItem.id)) {
                std::swap(item, destItem);
            }
        }
    }
}
