#ifndef TILEVARIANT_H
#define TILEVARIANT_H

enum class Variant {
    none,
    ankh,
    ash,
    ashWood,
    bone,
    corruption,
    crimson,
    crystal,
    dartLeft,
    dartRight,
    deadMans,
    desert,
    dirt,
    dryBone,
    dungeon,
    dynasty,
    flameLeft,
    flameRight,
    flesh,
    forest,
    frozen,
    gold,
    goldLocked,
    granite,
    hallowed,
    health,
    honey,
    ice,
    ivy,
    jungle,
    lesion,
    lihzahrd,
    livingWood,
    livingLeaf,
    mana,
    marble,
    meteorite,
    mushroom,
    obsidian,
    omega,
    palmWood,
    pyramid,
    reef,
    richMahogany,
    sandstone,
    shadow,
    skyware,
    snake,
    spear,
    spider,
    spikyBall,
    stone,
    superDartLeft,
    superDartRight,
    tundra,
    underworld,
    water
};

enum class Painting {
    // 2x3
    darkness,
    darkSoulReaper,
    trappedGhost,
    // 3x2
    demonsEye,
    livingGore,
    flowingMagma,
    // 3x3
    bloodMoonRising,
    boneWarp,
    gloryOfTheFire,
    handEarth,
    hangingSkeleton,
    impFace,
    ominousPresence,
    shiningMoon,
    skelehead,
    skellingtonJSkellingsworth,
    theCursedMan,
    theGuardiansGaze,
    theHangedMan,
    wallSkeleton,
    // 4x3
    catacomb1,
    catacomb2,
    catacomb3,
    catacomb4,
    catacomb5,
    catacomb6,
    catacomb7,
    catacomb8,
    catacomb9,
    // 6x4
    ancientTablet,
    dryadisque,
    facingTheCerebralMastermind,
    goblinsPlayingPoker,
    greatWave,
    impact,
    lakeOfFire,
    poweredByBirds,
    somethingEvilIsWatchingYou,
    sparky,
    starryNight,
    theCreationOfTheGuide,
    theDestroyer,
    theEyeSeesTheEnd,
    thePersistencyOfEyes,
    theScreamer,
    theTwinsHaveAwoken,
    trioSuperHeroes,
    unicornCrossingTheHallows,
};

#endif // TILEVARIANT_H
