#ifndef DATAID_H
#define DATAID_H

#include <array>

namespace TileID
{
enum {
    empty = -1,
    dirt = 0,
    stone = 1,
    grass = 2,
    ironOre = 6,
    copperOre = 7,
    goldOre = 8,
    silverOre = 9,
    lifeCrystal = 12,
    chest = 21,
    demonite = 22,
    corruptGrass = 23,
    ebonstone = 25,
    altar = 26,
    orbHeart = 31,
    clay = 40,
    sand = 53,
    ash = 57,
    hellstone = 58,
    mud = 59,
    jungleGrass = 60,
    sapphireStone = 63,
    rubyStone = 64,
    emeraldStone = 65,
    topazStone = 66,
    amethystStone = 67,
    diamondStone = 68,
    mushroomGrass = 70,
    ebonsand = 112,
    silt = 123,
    snow = 147,
    ice = 161,
    thinIce = 162,
    corruptIce = 163,
    tinOre = 166,
    leadOre = 167,
    tungstenOre = 168,
    platinumOre = 169,
    cloud = 189,
    livingWood = 191,
    leaf = 192,
    flesh = 195,
    rainCloud = 196,
    asphalt = 198,
    crimsonGrass = 199,
    crimsonIce = 200,
    sunplate = 202,
    crimstone = 203,
    crimtane = 204,
    slush = 224,
    hive = 225,
    lihzahrdBrick = 226,
    honey = 229,
    larva = 231,
    crimsand = 234,
    coralstone = 315,
    smoothMarble = 357,
    marble = 367,
    granite = 368,
    smoothGranite = 369,
    bubble = 379,
    lavaMossStone = 381,
    sandstone = 396,
    hardenedSand = 397,
    hardenedEbonsand = 398,
    hardenedCrimsand = 399,
    ebonsandstone = 400,
    crimsandstone = 401,
    desertFossil = 404,
    snowCloud = 460,
    lesion = 474,
    shellPile = 495,
    kryptonMossStone = 534,
    xenonMossStone = 536,
    argonMossStone = 539,
    neonMossStone = 625,
    heliumMossStone = 627,
    ashGrass = 633,
    corruptJungleGrass = 661,
    crimsonJungleGrass = 662,
    aetherium = 659
};
}

namespace WallID
{
enum { empty = 0 };

namespace Unsafe
{
enum {
    dirt = 2,
    ebonstone = 3,
    mud = 15,
    snow = 40,
    amethystStone = 48,
    topazStone = 49,
    sapphireStone = 50,
    emeraldStone = 51,
    rubyStone = 52,
    diamondStone = 53,
    rockyDirt = 59,
    oldStone = 61,
    spider = 62,
    grass = 63,
    jungle = 64,
    flower = 65,
    corruptGrass = 69,
    ice = 71,
    mushroom = 80,
    crimsonGrass = 81,
    crimstone = 83,
    hive = 86,
    caveDirt = 170,
    roughDirt = 171,
    marble = 178,
    granite = 180,
    craggyStone = 185,
    sandstone = 187,
    corruptGrowth = 188,
    corruptMass = 189,
    corruptPustule = 190,
    corruptTendril = 191,
    crimsonCrust = 192,
    crimsonScab = 193,
    crimsonTeeth = 194,
    crimsonBlister = 195,
    layeredDirt = 196,
    crumblingDirt = 197,
    crackedDirt = 198,
    wavyDirt = 199,
    lichenStone = 204,
    leafyJungle = 205,
    ivyStone = 206,
    jungleVine = 207,
    ember = 208,
    cinder = 209,
    magma = 210,
    smoulderingStone = 211,
    wornStone = 212,
    stalactiteStone = 213,
    mottledStone = 214,
    fracturedStone = 215,
    hardenedSand = 216,
    hardenedEbonsand = 217,
    hardenedCrimsand = 218,
    ebonsandstone = 220,
    crimsandstone = 221,
    livingWood = 244,
};
}
} // namespace WallID

namespace WallVariants
{
inline std::array const dirt = {
    WallID::Unsafe::dirt,
    WallID::Unsafe::rockyDirt,
    WallID::Unsafe::caveDirt,
    WallID::Unsafe::roughDirt,
    WallID::Unsafe::layeredDirt,
    WallID::Unsafe::crumblingDirt,
    WallID::Unsafe::crackedDirt,
    WallID::Unsafe::wavyDirt};

inline std::array const stone = {
    WallID::Unsafe::oldStone,
    WallID::Unsafe::craggyStone,
    WallID::Unsafe::wornStone,
    WallID::Unsafe::stalactiteStone,
    WallID::Unsafe::mottledStone,
    WallID::Unsafe::fracturedStone};

inline std::array const jungle = {
    WallID::Unsafe::mud,
    WallID::Unsafe::lichenStone,
    WallID::Unsafe::leafyJungle,
    WallID::Unsafe::ivyStone,
    WallID::Unsafe::jungleVine};

// Excludes: crimsonBlister
inline std::array const crimson = {
    WallID::Unsafe::crimstone,
    WallID::Unsafe::crimsonCrust,
    WallID::Unsafe::crimsonScab,
    WallID::Unsafe::crimsonTeeth};

// Excludes: corruptTendril
inline std::array const corruption = {
    WallID::Unsafe::ebonstone,
    WallID::Unsafe::corruptGrowth,
    WallID::Unsafe::corruptMass,
    WallID::Unsafe::corruptPustule};

inline std::array const underworld = {
    WallID::Unsafe::ember,
    WallID::Unsafe::cinder,
    WallID::Unsafe::magma,
    WallID::Unsafe::smoulderingStone};
} // namespace WallVariants

namespace ItemID
{
enum {
    torch = 8,
    wood = 9,
    copperBar = 20,
    ironBar = 22,
    lesserHealingPotion = 28,
    bottle = 31,
    woodenArrow = 40,
    shuriken = 42,
    silverCoin = 72,
    goldCoin = 73,
    grenade = 168,
    throwingKnife = 279,
    spear = 280,
    blowpipe = 281,
    glowstick = 282,
    woodenBoomerang = 284,
    aglet = 285,
    swiftnessPotion = 290,
    ironskinPotion = 292,
    shinePotion = 298,
    nightOwlPotion = 299,
    demonTorch = 433,
    tinBar = 703,
    leadBar = 704,
    umbrella = 946,
    climbingClaws = 953,
    rope = 965,
    iceTorch = 974,
    miningPotion = 2322,
    builderPotion = 2325,
    recallPotion = 2350,
    vineRope = 2996,
    boneTorch = 3004,
    guideToPlantFiberCordage = 3068,
    wandOfSparking = 3069,
    webRope = 3078,
    radar = 3084,
    herbBag = 3093,
    stepStool = 4341,
    canOfWorms = 4345,
    desertTorch = 4383,
    coralTorch = 4384,
    corruptTorch = 4385,
    crimsonTorch = 4386,
    jungleTorch = 4388,
    mushroomTorch = 5293,
    aetherTorch = 5353,
};
}

namespace Prefix
{
enum {
    none = 0,
    large = 1,
    massive = 2,
    dangerous = 3,
    savage = 4,
    sharp = 5,
    pointy = 6,
    bulky = 12,
    heavy = 14,
    light = 15,
    sighted = 16,
    rapid = 17,
    hasty_ranged = 18,
    intimidating = 19,
    deadly_ranged = 20,
    staunch = 21,
    powerful = 25,
    mystic = 26,
    adept = 27,
    masterful = 28,
    intense = 32,
    taboo = 33,
    celestial = 34,
    furious = 35,
    keen = 36,
    superior = 37,
    forceful = 38,
    quick_common = 42,
    deadly_common = 43,
    agile = 44,
    nimble = 45,
    murderous = 46,
    nasty = 51,
    manic = 52,
    hurtful = 53,
    strong = 54,
    unpleasant = 55,
    ruthless = 57,
    frenzying = 58,
    godly = 59,
    demonic = 60,
    zealous = 61,
    hard = 62,
    guarding = 63,
    armored = 64,
    warding = 65,
    arcane = 66,
    precise = 67,
    lucky = 68,
    jagged = 69,
    spiked = 70,
    angry = 71,
    menacing = 72,
    brisk = 73,
    fleeting = 74,
    hasty_accessory = 75,
    quick_accessory = 76,
    wild = 77,
    rash = 78,
    intrepid = 79,
    violent = 80,
    legendary = 81,
    unreal = 82,
    mythical = 83
};
}

namespace PrefixSet
{
inline std::array const accessory = {
    Prefix::none,
    Prefix::hard,
    Prefix::guarding,
    Prefix::armored,
    Prefix::warding,
    Prefix::precise,
    Prefix::lucky,
    Prefix::jagged,
    Prefix::spiked,
    Prefix::angry,
    Prefix::menacing,
    Prefix::brisk,
    Prefix::fleeting,
    Prefix::hasty_accessory,
    Prefix::quick_accessory,
    Prefix::wild,
    Prefix::rash,
    Prefix::intrepid,
    Prefix::violent,
    Prefix::arcane};

inline std::array const universal = {
    Prefix::none,
    Prefix::keen,
    Prefix::superior,
    Prefix::forceful,
    Prefix::hurtful,
    Prefix::strong,
    Prefix::unpleasant,
    Prefix::ruthless,
    Prefix::godly,
    Prefix::demonic,
    Prefix::zealous};

inline std::array const common = {
    Prefix::none,
    Prefix::keen,
    Prefix::superior,
    Prefix::forceful,
    Prefix::hurtful,
    Prefix::strong,
    Prefix::unpleasant,
    Prefix::ruthless,
    Prefix::godly,
    Prefix::demonic,
    Prefix::zealous,
    Prefix::quick_common,
    Prefix::deadly_common,
    Prefix::agile,
    Prefix::nimble,
    Prefix::murderous,
    Prefix::nasty};

inline std::array const melee = {
    Prefix::none,          Prefix::keen,      Prefix::superior,
    Prefix::forceful,      Prefix::hurtful,   Prefix::strong,
    Prefix::unpleasant,    Prefix::ruthless,  Prefix::godly,
    Prefix::demonic,       Prefix::zealous,   Prefix::quick_common,
    Prefix::deadly_common, Prefix::agile,     Prefix::nimble,
    Prefix::murderous,     Prefix::nasty,     Prefix::large,
    Prefix::massive,       Prefix::dangerous, Prefix::savage,
    Prefix::sharp,         Prefix::pointy,    Prefix::bulky,
    Prefix::heavy,         Prefix::light,     Prefix::legendary};

inline std::array const ranged = {
    Prefix::none,         Prefix::keen,         Prefix::superior,
    Prefix::forceful,     Prefix::hurtful,      Prefix::strong,
    Prefix::unpleasant,   Prefix::ruthless,     Prefix::godly,
    Prefix::demonic,      Prefix::zealous,      Prefix::quick_common,
    Prefix::agile,        Prefix::nimble,       Prefix::murderous,
    Prefix::nasty,        Prefix::sighted,      Prefix::rapid,
    Prefix::hasty_ranged, Prefix::intimidating, Prefix::deadly_ranged,
    Prefix::staunch,      Prefix::powerful,     Prefix::frenzying,
    Prefix::unreal};

inline std::array const magic = {
    Prefix::none,          Prefix::keen,      Prefix::superior,
    Prefix::forceful,      Prefix::hurtful,   Prefix::strong,
    Prefix::unpleasant,    Prefix::ruthless,  Prefix::godly,
    Prefix::demonic,       Prefix::zealous,   Prefix::quick_common,
    Prefix::deadly_common, Prefix::agile,     Prefix::nimble,
    Prefix::murderous,     Prefix::nasty,     Prefix::mystic,
    Prefix::adept,         Prefix::masterful, Prefix::intense,
    Prefix::taboo,         Prefix::celestial, Prefix::furious,
    Prefix::manic,         Prefix::mythical};
} // namespace PrefixSet

#endif // DATAID_H
